// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjlymownokhevndhzfpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbHltb3dub2toZXZuZGh6ZnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTQxMzUsImV4cCI6MjA1OTk5MDEzNX0.36838pKVNvE1iHc7Fll27HEvEp3trhUCD3PKbjxg_Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);